"""Added color code to emails sent

Revision ID: 01d05d156d23
Revises: 9873eedfc63b
Create Date: 2023-12-19 00:44:19.118695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01d05d156d23'
down_revision = '9873eedfc63b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emails_sent', schema=None) as batch_op:
        batch_op.add_column(sa.Column('template_color_code', sa.String(length=80), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emails_sent', schema=None) as batch_op:
        batch_op.drop_column('template_color_code')

    # ### end Alembic commands ###
