"""Fixed typo

Revision ID: 1fd91bb06fa2
Revises: 6cd76901f9b0
Create Date: 2023-12-19 02:51:08.885788

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1fd91bb06fa2'
down_revision = '6cd76901f9b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.String(length=80), nullable=False))
        batch_op.drop_column('data')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data', mysql.VARCHAR(length=80), nullable=False))
        batch_op.drop_column('date')

    # ### end Alembic commands ###
