"""Added jsonConstruct column for Unlayer conf JSON

Revision ID: 338685d6c4d0
Revises: b79b7db517dc
Create Date: 2024-01-12 17:45:01.710173

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '338685d6c4d0'
down_revision = 'b79b7db517dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_templates', schema=None) as batch_op:
        batch_op.alter_column('jsonConstruct',
               existing_type=mysql.TEXT(),
               type_=sa.JSON(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_templates', schema=None) as batch_op:
        batch_op.alter_column('jsonConstruct',
               existing_type=sa.JSON(),
               type_=mysql.TEXT(),
               existing_nullable=False)

    # ### end Alembic commands ###
