"""Set every content column to TEXT

Revision ID: 9873eedfc63b
Revises: a2f1584293f5
Create Date: 2023-12-17 20:45:20.655218

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9873eedfc63b'
down_revision = 'a2f1584293f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_templates', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=mysql.VARCHAR(length=1500),
               type_=sa.TEXT(),
               existing_nullable=False)

    with op.batch_alter_table('emails_sent', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=mysql.VARCHAR(length=1500),
               type_=sa.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emails_sent', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               type_=mysql.VARCHAR(length=1500),
               existing_nullable=True)

    with op.batch_alter_table('email_templates', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               type_=mysql.VARCHAR(length=1500),
               existing_nullable=False)

    # ### end Alembic commands ###
