"""Removed content field from email templates table

Revision ID: 9b2e65286bda
Revises: 338685d6c4d0
Create Date: 2024-01-12 19:07:32.809176

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9b2e65286bda'
down_revision = '338685d6c4d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_templates', schema=None) as batch_op:
        batch_op.drop_column('content')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', mysql.TEXT(), nullable=False))

    # ### end Alembic commands ###
