"""Added username to EmailsSent

Revision ID: a2f1584293f5
Revises: 2a06ff8b7201
Create Date: 2023-12-17 19:58:32.694092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2f1584293f5'
down_revision = '2a06ff8b7201'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emails_sent', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=80), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emails_sent', schema=None) as batch_op:
        batch_op.drop_column('username')

    # ### end Alembic commands ###
