"""Added jsonConstruct column for Unlayer conf

Revision ID: b79b7db517dc
Revises: efa230f88270
Create Date: 2024-01-11 17:51:06.753025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b79b7db517dc'
down_revision = 'efa230f88270'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jsonConstruct', sa.TEXT(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_templates', schema=None) as batch_op:
        batch_op.drop_column('jsonConstruct')

    # ### end Alembic commands ###
