"""Corrected emails_sent bookingsID column --> id type int to string

Revision ID: c9a5bd427eeb
Revises: fbca75778b95
Create Date: 2023-12-12 17:23:23.711109

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c9a5bd427eeb'
down_revision = 'fbca75778b95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emails_sent', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bookingID', sa.String(length=120), nullable=False))
        batch_op.drop_column('bookingsID')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emails_sent', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bookingsID', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('bookingID')

    # ### end Alembic commands ###
