"""added user and booking cliniko id to EmailsSent table

Revision ID: e8392dbe4e50
Revises: c9a5bd427eeb
Create Date: 2023-12-12 17:37:07.011240

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e8392dbe4e50'
down_revision = 'c9a5bd427eeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cliniko_id', sa.String(length=120), nullable=False))
        batch_op.drop_column('ciliniko_id')

    with op.batch_alter_table('emails_sent', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_cliniko_id', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('booking_cliniko_id', sa.String(length=120), nullable=False))
        batch_op.drop_index('userID')
        batch_op.drop_column('userID')
        batch_op.drop_column('bookingID')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cliniko_id', sa.String(length=120), nullable=False))
        batch_op.drop_column('ciliniko_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ciliniko_id', mysql.VARCHAR(length=120), nullable=False))
        batch_op.drop_column('cliniko_id')

    with op.batch_alter_table('emails_sent', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bookingID', mysql.VARCHAR(length=120), nullable=False))
        batch_op.add_column(sa.Column('userID', mysql.VARCHAR(length=120), nullable=True))
        batch_op.create_index('userID', ['userID'], unique=False)
        batch_op.drop_column('booking_cliniko_id')
        batch_op.drop_column('user_cliniko_id')

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ciliniko_id', mysql.VARCHAR(length=120), nullable=False))
        batch_op.drop_column('cliniko_id')

    # ### end Alembic commands ###
